version: '3.5'

services:
  app:
    build: ./app/
    ports:
      - 8000:3000
    volumes:
      - ./app/package.json:/usr/src/package.json
      - ./app/:/usr/src/
      - /usr/src/node_modules
    networks:
      - tarot_game

networks:
  tarot_game:
    name: tarot-game

